services:
  gluetun:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun
    # External Container --> https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
    #  # SetUp --> https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=vyprvpn
      - OPENVPN_USER=avinash@eachence.com
      - OPENVPN_PASSWORD=9Lu>?XC%rGj:H,n
      - SERVER_REGIONS=india
      - TZ=Asia/Kolkata
      - FIREWALL_VPN_INPUT_PORTS=80,8090,52496
    ports:
      - "80:80"
      - "8090:8090"
      - "52496:52496"
    restart: always
  app:
    build: .
    network_mode: "service:gluetun" #If using VPN, Remove the Hash from first and fill up Above Details.
    command: bash start.sh
    restart: always
